# Generated by Django 2.0.9 on 2019-01-22 14:05

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtailnhsukfrontend.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('action_link', wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock(label='link text', required=True)), ('external_url', wagtail.blocks.URLBlock(label='external URL', required=True))])), ('care_card', wagtail.blocks.StructBlock([('type', wagtail.blocks.ChoiceBlock(choices=[('primary', 'Primary'), ('urgent', 'Urgent'), ('immediate', 'Immediate')])), ('title', wagtail.blocks.CharBlock(required=True)), ('body', wagtail.blocks.RichTextBlock(required=True))])), ('details', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=True)), ('body', wagtail.blocks.RichTextBlock(required=True))])), ('do_list', wagtail.blocks.StructBlock([('do', wagtail.blocks.ListBlock(wagtail.blocks.field_block.RichTextBlock))])), ('dont_list', wagtail.blocks.StructBlock([('dont', wagtail.blocks.ListBlock(wagtail.blocks.field_block.RichTextBlock))])), ('expander', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=True)), ('body', wagtail.blocks.RichTextBlock(required=True))])), ('expander_group', wagtail.blocks.StructBlock([('expanders', wagtail.blocks.ListBlock(wagtailnhsukfrontend.blocks.ExpanderBlock))])), ('inset_text', wagtailnhsukfrontend.blocks.InsetTextBlock()), ('image', wagtail.blocks.StructBlock([('content_image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('alt_text', wagtail.blocks.CharBlock(help_text='Only leave this blank if the image is decorative.', required=False)), ('caption', wagtail.blocks.CharBlock(required=False))])), ('panel', wagtail.blocks.StructBlock([('labeled_title', wagtail.blocks.CharBlock(required=False)), ('body', wagtail.blocks.RichTextBlock(required=True))])), ('warning_callout', wagtailnhsukfrontend.blocks.WarningCalloutBlock())]),
            preserve_default=False,
        ),
    ]
